ephysPaths ={'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\pre',...
    'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\run1', ...
    'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\run2', ...
    'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\run3', ...
    'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\run4', ...
    'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\post1', ...
    'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs\post2'};
savePath = 'G:\vGAT_CreCh2_4\ForcedD3FreeD1\LFPs';