SpkPaths ={'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\presleep',...
    'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\run1', ...
    'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\run2', ...
    'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\run3', ...
    'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\run4', ...
    'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\postsleep1', ...
    'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes\postsleep2'};
savePath = 'D:\vGAT_CreCh2_4\ForcedD3FreeD1\OEspikes';